
#服务器
server:
  port: 8080
# mysql 的数据库配置
spring:
  datasource:
    url: jdbc:mysql://47.96.92.253:3306/zn_share?charset=utf8mb4&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=Hongkong
    username: root
    password: myroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

#配置日志
logging:
  level:
    com.kwon.znshare.job: info #不同目录下的日志可配置不同级别
    org.springfromework.web: info
  #配置日志文件路径
  file: log\myspringboot.log



#spring.datasource.tomcat.max-active=20
#spring.datasource.tomcat.test-while-idle=true
#spring.datasource.tomcat.validation-query=select 1
#spring.datasource.tomcat.default-auto-commit=false
#spring.datasource.tomcat.min-idle=15
#spring.datasource.tomcat.initial-size=15

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jackson.serialization.indent-output=true